### ISSUE TITLE
Where to download the foo_1.fq.gz and foo_2.fq.gz file?

### ISSUE THREAD

**Issue by zhaozhang** [KHP-Informatics/ngseasy#7]
Hi,

I am following the instruction in readme to make ngseasy working. I am running into a problem: where can I download the sample fastaq files? foo_1.fq.gz and foo_2.fq.gz? I am new to this area. Thanks.

Best,
Zhao

**Comment by snewhouse** [comment]
Hi
Sorry about this..
Can you send me the list of commands you are running please?

If you are using the Makefile, as shown below:- 

``` bash
cd /home/${USER}
git clone https://github.com/KHP-Informatics/ngseasy.git
cd ngseasy
make INTSALLDIR="/home/${USER}" all
sudo make install
```

This should get you all you need.

Test Data also at [illumina.100bp.pe.wex.30x_1.fastq.gz](https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_1.fastq.gz) and [/illumina.100bp.pe.wex.30x_2.fastq.gz](https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_2.fastq.gz).

Thanks for downloading and having a go. 

NSGeasy is under heavy dev and there are some teething problems and we need folks to donwload, test and report bugs, in order to make this all even better

Cheer

Steve & Amos

**Comment by zhaozhang** [comment]
Hi, 

Thanks a lot for the clarification.

Best,
Zhao
